name: setup rclone action
description: download and unpack rclone for gh actions
inputs:
  conf:
    description: rclone conf encoded in base64
    default: false

runs:
  using: composite
  steps:
    - name: resolve url, download and unpack rclone
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: |
        $response = Invoke-RestMethod -Uri "https://api.github.com/repos/rclone/rclone/releases/latest"
        $asset = $response.assets | Where-Object { $_.name -match 'windows-amd64.zip' }
        Invoke-WebRequest -Uri $asset.browser_download_url
        ls
        Expand-Archive -Path $asset.name

    - name: rclone.conf from secret
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: |
        [IO.File]::WriteAllBytes("rclone\rclone.conf", [Convert]::FromBase64String($env:conf))
      env:
        conf: ${{ inputs.conf }}

    - name: add rclone to path
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: echo ${{ runner.temp }}\rclone>> $GITHUB_PATH
